#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

pattern="^(feat|fix|docs|refactor|test|chore)(\(.+\))?: .+"

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
  echo "❌ Invalid commit message."
  echo ""
  echo "Use Conventional Commits:"
  echo "feat: add authentication"
  echo "fix: resolve null pointer"
  echo "docs: update readme"
  exit 1
fi