# Import environment variables from .env file
spring.config.import=optional:file:.env

# server.port=8080

# Application Name (Optional, can also come from env)
spring.application.name=${APP_NAME:mediguk_backend}

# Database Configuration using Environment Variables
spring.datasource.url=jdbc:${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JW secret key 
jwt.secret=${JW_SECRET}
